In [1]:
import os
os.chdir(r'/Users/zhanghui/商业分析工具和应用/Python/Python_book/13Dimensionality_reduction')

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
profile = pd.read_csv('profile_telecom.csv')
profile.head()

ID  cnt_call  cnt_msg  cnt_wei  cnt_web
0  1964627        46       90       36       31
1  3107769        53        2        0        2
2  3686296        28       24        5        8
3  3961002         9        2        0        4
4  4174839       145        2        0        1

# 主成分分析

In [4]:
#分析变量之间的关系
data = profile.ix[:,'cnt_call':]

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  
/Applications/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)


In [5]:
data.corr(method = 'pearson')

cnt_call   cnt_msg   cnt_wei   cnt_web
cnt_call  1.000000  0.052096  0.117832  0.114190
cnt_msg   0.052096  1.000000  0.510686  0.739506
cnt_wei   0.117832  0.510686  1.000000  0.950492
cnt_web   0.114190  0.739506  0.950492  1.000000

In [8]:
#数据标准化
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA


data_scaled = scale(data)
pca = PCA(n_components = 2, whiten = True).fit(data_scaled)
pca.explained_variance_ratio_

array([0.62510442, 0.24620209])

In [10]:
#每个主成分在原始变量上的权重
pca.components_ 

array([[ 0.11085805,  0.50974123,  0.57909319,  0.62651852],
       [ 0.99020127, -0.12736724, -0.01900236, -0.05401806]])

In [11]:
#每个样本的主成分得分，横着看
pca.transform(data_scaled)

array([[ 2.30183615, -0.89716788],
       [-0.74694076, -0.04035188],
       [-0.11502116, -0.59578592],
       ...,
       [ 2.19333782,  0.04953167],
       [-0.07833419, -0.10944885],
       [-0.6621524 ,  1.16641367]])

# 因子分析
四个步骤：
数据导入与转换
抽取主成分
确定保留因子的个数
进行因子旋转

In [16]:
cities = pd.read_csv('cities_10.csv',encoding = 'gbk')
cities

AREA       X1     X2      X3      X4      X5      X6      X7      X8      X9
0   辽宁   5458.2  13000  1376.2  2258.4  1315.9   529.0  2258.4   123.7   399.7
1   山东  10550.0  11643  3502.5  3851.0  2288.7  1070.7  3181.9   211.1   610.2
2   河北   6076.6   9047  1406.7  2092.6  1161.6   597.1  1968.3    45.9   302.3
3   天津   2022.6  22068   822.8   960.0   703.7   361.9   941.4   115.7   171.8
4   江苏  10636.3  14397  3536.3  3967.2  2320.0  1141.3  3215.8   384.7   643.7
5   上海   5408.8  40627  2196.2  2755.8  1970.2   779.3  2035.2   320.5   709.0
6   浙江   7670.0  16570  2356.5  3065.0  2296.6  1180.6  2877.5   294.2   566.9
7   福建   4682.0  13510  1047.1  1859.0   964.5   397.9  1663.3   173.7   272.9
8   广东  11769.7  15030  4224.6  4793.6  3022.9  1275.5  5013.6  1843.7  1201.6
9   广西   2455.4   5062   367.0   995.7   542.2   352.7  1025.5    15.1   186.7

In [17]:
cities.corr(method = 'pearson')
#我们会发现多数变量值关键存在着明显的线性相关关系，因此可以运用因子分析对数据进行降维

X1        X2        X3        X4        X5        X6        X7  \
X1  1.000000 -0.094292  0.966506  0.979238  0.922984  0.921680  0.941148   
X2 -0.094292  1.000000  0.112726  0.074167  0.214052  0.093483 -0.042776   
X3  0.966506  0.112726  1.000000  0.985373  0.963159  0.939194  0.935196   
X4  0.979238  0.074167  0.985373  1.000000  0.972862  0.939720  0.962267   
X5  0.922984  0.214052  0.963159  0.972862  1.000000  0.971337  0.937109   
X6  0.921680  0.093483  0.939194  0.939720  0.971337  1.000000  0.897127   
X7  0.941148 -0.042776  0.935196  0.962267  0.937109  0.897127  1.000000   
X8  0.637458  0.081195  0.704714  0.713890  0.716722  0.624294  0.836272   
X9  0.825568  0.273145  0.898016  0.913364  0.934549  0.848004  0.928692   

          X8        X9  
X1  0.637458  0.825568  
X2  0.081195  0.273145  
X3  0.704714  0.898016  
X4  0.713890  0.913364  
X5  0.716722  0.934549  
X6  0.624294  0.848004  
X7  0.836272  0.928692  
X8  1.000000  0.881528  
X9  0.881528  1.000000

In [18]:
from sklearn.preprocessing import scale

scale_cities = scale(cities.ix[:,'X1':])
pca_c = PCA(n_components = 3,whiten = True).fit(scale_cities)
pca_c.explained_variance_ratio_

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until
/Applications/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)


array([0.80112955, 0.12214932, 0.0607924 ])

为了确定因子个数，先对数据进行主成分分析，主成分分析前需要先进行标准化处理数据。
根据结果可知，我们保留两个主成分可以使解释的数据变异提升到92%

In [21]:
#输入数据并进行主成分提取
from fa_kit import FactorAnalysis
from fa_kit import plotting as fa_plotting
fa = FactorAnalysis.load_data_samples(data,
                                     preproc_demean = True,
                                     preproc_scale = True)
fa.extract_components()

SyntaxError: invalid syntax (<ipython-input-21-7ea702f66756>, line 2)

In [ ]:
#确定保留因子的数量
fa.find_comps_to_retain(method = 'top_n',num_keep=2)

In [ ]:
#使用最大方差法进行因子旋转
fa.rotate_component(method = 'varimax')
fa.plotting.graph_summary(fa)

In [ ]:
#因子载荷矩阵
pd.DataFrame(fa.comps['rot'])

In [ ]:
import numpy as np
fas = pd.DataFrame(fa.comps['rot'])
data = pd.DataFrame(data)
score = pd.DataFrame(np.dot(data,fas))

a = score.rename(columns = {0:'Gross',1:'Avg'})
citi10_fa = model_data.join(a)